[package]
name = "everlend-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
thiserror = "1.0"
solana-program = "1.9.2"
spl-token = { version = "3.1", features = [ "no-entrypoint" ] }
spl-token-lending = { git = "https://github.com/everlend/solana-program-library", features = [ "no-entrypoint" ] }
port-variable-rate-lending-instructions = "0.2.9"
larix-lending = { git = "https://github.com/ProjectLarix/larix-lending", features = [ "no-entrypoint" ], branch = "lp-v2" }
borsh = "0.9.0"

[dev-dependencies]
solana-sdk = "1.9.2"

[lib]
crate-type = ["cdylib", "lib"]
