[workspace]
members = [
  "utils",
  "depositor/program",
  "depositor/cli",
  "ulp/program",
  "ulp/cli",
  "liquidity_oracle/program",
  "income_pools/program",
  "income_pools/cli",
  "registry/program",
  "tests",
  "e2e",
]
