[workspace]
members = [
  "utils",
  "depositor",
  "liquidity_oracle",
  "general_pool",
  "income_pools",
  "registry",
  "tests",
  "toolkit",
  "rewards"
]

[profile.release]
overflow-checks = true