name: Programs

on:
  push:
    branches:
      - 'main'
      - 'v1'
  pull_request:
    branches:
      - 'main'
      - 'v1'

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 1.10.6
  RUST_TOOLCHAIN: stable

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      cache_id: programs

    steps:
      # Setup Deps
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-linux-build-deps
      - uses: ./.github/actions/install-solana
        with:
          solana_version: ${{ env.SOLANA_VERSION }}
      - uses: ./.github/actions/install-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      # Restore Cache from previous build/test
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./programs/target
          key: ${{ env.cache_id }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUSTC_HASH }}

      - uses: ./.github/actions/build-programs

      # Run test
      - name: test-programs
        id: run_test
        working-directory: ./programs/tests
        run: |
          cargo +${{ env.RUST_TOOLCHAIN }} test-bpf --version
          cargo +${{ env.RUST_TOOLCHAIN }} test-bpf --test tests -- --nocapture --test-threads 1
